- hosts: brian-demo-dtw4
  gather_facts: no
  become: yes
  become_method: sudo
  tasks:
  - name: copy init files
    copy:
      src: ../files/init
      dest: /tmp/

  - name: create secret
    shell: cd /tmp/init/secret && sh gen_secret.sh &&  kubectl apply -f /tmp/init/secret

  - name: create nginx demo
    shell: cd /tmp/init/secret && sh gen_secret.sh &&  kubectl apply -f /tmp/init/ingress

  - name: clean tmp folder
    shell: rm -rf /tmp/init
