- hosts: ayla-master-perf-gfg2
  gather_facts: no
  become: yes
  become_method: sudo
  tasks:
  - name: copy init files
    copy:
      src: ../files/init
      dest: /tmp/

  - name: add user docker & kubectl permission
    shell: sudo gpasswd -a ubuntu docker && sudo newgrp - docker && sudo cp -r /root/.kube /home/ubuntu/ && sudo chown -R ubuntu:ubuntu /home/ubuntu/.kube

  - name: create init secret
    shell: kubectl apply -f /tmp/init/secret

  - name: kube-proxy version update to 1.13.1
    shell: kubectl apply -f /tmp/init/kube-proxy

