- hosts: k8s-cluster
  gather_facts: no
  become: yes
  become_method: sudo
  tasks:
  - name: backup files
    shell: cp /etc/sysctl.conf /etc/sysctl.conf.bak && cp /etc/security/limits.conf /etc/security/limits.conf.bak

  - name: copy sysctl.conf
    copy:
      src: ../performance/sysctl.conf
      dest: /etc/sysctl.conf

  - name: copy limits.conf
    copy:
      src: ../performance/limits.conf
      dest: /etc/security/limits.conf
