apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: nexus-cn-secret
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5heWxhLmNvbS5jbiI6eyJVc2VybmFtZSI6ImF5bGEiLCJQYXNzd29yZCI6Ikh2VmtMS2g4cDYyTnUzUzkiLCJFbWFpbCI6ImRldm9wc0BheWxhbmV0d29ya3MuY29tIn19fQ==
