apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: secret-demo
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5leGFtcGxlLmNvbSI6eyJVc2VybmFtZSI6ImFkbWluIiwiUGFzc3dvcmQiOiJkZW1vIiwiRW1haWwiOiIifX19JQo=
